### PR TITLE
Compatibility with Windows and node.js 0.12, io.js

### LINKED ISSUE #1: Enable calls to omit the device name and return the first non loopback devices mac address

### PR DESCRIPTION
**Pull request by jpommerening**
Hi,

here's a whole bunch of changes, but I rebased them so that there is roughly one feature per commit.
It looks like it has been some time since anything happened here. I'm not sure you're interested in these changes (or maintaining `netif` at all), so pick what you like!

d4ebe34 introduces compatibility with node.js 0.12 and newer using [nan](/nodejs/nan)
933c742 adds [node-pre-gyp](/mapbox/node-pre-gyp) to the build process, allowing to provide pre-compiled binary packages, but falling back to building from source during installation
7f7dbcd restructures the tests so they don't rely on specific network interface names
ae66382 adds windows compatibility
59786e9 adds an [appveyor](https://ci.appveyor.com/project/jpommerening/node-netif) configuration
f9bde6a adds deployment steps to the Travis and Appveyor builds to upload the compiled node.js bindings to GitHub (my test release: [v0.2.0-rc6](/jpommerening/node-netif/releases/tag/v0.2.0-rc6), note: this is still using my GitHub [API tokens](https://github.com/settings/tokens))
d6918b0 resolves #1 ;)

If you don't like these changes, just let me know. I can maintain my own fork and release it under a different name. Otherwise, ask my anything, I'm happy to explain each of these changes in detail!

_Edit:_ I couldn't find a way to get this to work under node.js 0.8. There's always a dependency deep down in the dep-tree that is using the caret (`^`) notation, not supported by old `npm`.

### CODE REVIEW

**Comment by jpommerening** [comment]
Oh, I also tested this against the two dependants I could [find](https://github.com/search?utf8=%E2%9C%93&q=extension%3Ajson+path%3A%2F+netif) on GitHub: [unid](/chapel/unid) and [flake](/chilts/flake). Both seem to work just fine.
I also have access to an ancient Solaris 10 machine but was unable to get node.js running there.

**Comment by wolfeidau** [comment]
Hey how about i just add you as a maintainer to this project?

I don't do a lot with it at the moment.

I think I can also add you on NPM if you want to publish it.

**Comment by jpommerening** [comment]
That would be super awesome!

Would if be of if I'll take care of winding up work here (replacing the deploy keys in `.travis.yml` & `.appveyor.yml`) and release 0.2.0 then?

**Comment by wolfeidau** [comment]
I have added you to the project.

I am not sure I understand that last sentence, if you want me to help just ping me.

What is your npm username?

**Comment by jpommerening** [comment]
Thanks! :sparkles:

I was trying to say that I wanted to fix the GitHub API keys (*) inside the `.travis.yml` ([L19](https://github.com/jpommerening/node-netif/commit/f9bde6a17841159728fd1b848654d5a07c0c0615#diff-354f30a63fb0907d4ad57269548329e3R19)) and `.appveyor.yml` ([L38](https://github.com/jpommerening/node-netif/commit/f9bde6a17841159728fd1b848654d5a07c0c0615#diff-11c909939117928998b102a1fff7d363R38)) files because I think the encryption scheme is repo-specific.

After that, I'll let you have a look and, if you don't mind, we can release 0.2.0.

npmjs: https://www.npmjs.com/~jpommerening

(*) which I'm using to push the compiled native stuff to GitHub when Travis/Appveyor is building a tag. (So we don't need to spin up a Windows VM to do a release. Just tag, and wait for the files to appear on the GitHub releases page. Of course we could skip that step entirely and just let the user compile the `netif.cc` file themselves.)

**Comment by wolfeidau** [comment]
OK added on NPM as well.

```
node-netif$ npm owner ls netif
wolfeidau <mark@wolfe.id.au>
jpommerening <jonas.pommerening@gmail.com>
```

**Comment by jpommerening** [comment]
Thanks, I'll give it a shot :)

**Pull request merged**
